Name: DeviceSettingsWidget
Type: FolderType
Children:
- Name: DeviceSettingsWidget
  Id: g=91302d976ee7bf8d51bde6add8b89130
  Supertype: Screen
  ReferenceType: HasComponent
  Children:
  - Name: HorizontalAlignment
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
  - Name: VerticalAlignment
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 400.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 240.0
  - Name: NavigationPanel1
    Type: NavigationPanel
    Children:
    - Name: Panels
      Type: BaseObjectType
      Children:
      - Name: Panel1
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":40,"TextId":"Configuration"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/FeaturesDemo2_Dani_v3/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Configuration"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":8}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel2
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":40,"TextId":"ProductInformation"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/FeaturesDemo2_Dani_v3/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Product_Information"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":8}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel3
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":40,"TextId":"Diagnostics"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/FeaturesDemo2_Dani_v3/UI/SettingsWidgets/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Diagnostics"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":8}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
    - Name: CurrentPanel
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Children:
      - Name: Kind
        Type: PropertyType
        DataType: NodeId
        Value: {"Id":6,"Namespace":8}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 304.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 240.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: BottomMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
    - Name: CurrentTabIndex
      Type: BaseDataVariableType
      DataType: Int32
    - Class: Reference
      Target: ns=7;i=1181
      Direction: Forward
    - Class: Reference
      Target: ns=7;i=1183
      Direction: Forward
  - Name: SystemNode
    Type: NodePointer
    DataType: NodeId
    Value: {"IdType":2,"Id":"ec6e454a68ebbe1d2909d93aa145ec1b","Namespace":40}
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: "/Types/ObjectTypes/BaseObjectType/System"
  - Name: DeviceSettingsWidgetLogic
    Type: NetLogic
- File: DeviceSettingsWidgetComponents/DeviceSettingsWidgetComponents.yaml
